In [1]:
import torch

In [2]:
import torchvision

In [3]:
print(torch.cuda.is_available())

False


## Cells above is just a checking if PyTorch and CUDA are installed
[more in original utube video](https://www.youtube.com/watch?v=CNuI8OWsppg)

In [4]:
#1-D tensor
a = torch.tensor([2,2,1])
print(a)

tensor([2, 2, 1])


In [5]:
#2-D tensor
b = torch.tensor([[1,2,3], [2,2,1], [4,7,8], [0,0,0]])
print(b)

tensor([[1, 2, 3],
        [2, 2, 1],
        [4, 7, 8],
        [0, 0, 0]])


In [6]:
#type of tensor
print(a.shape) #or a.shape
print(b.shape)
print(a.size())
print(b.size()) #shape and size() does the same thing. just shape is an attribute and size() is a method

torch.Size([3])
torch.Size([4, 3])
torch.Size([3])
torch.Size([4, 3])


In [7]:
#get the height/number of rows in a tensor - 
print(b.shape[0]) #note: b.size([0]) will lead to an error; [0] indexed is because the rows are in [0] index
#or we can do b.shape[0]

4


In [8]:
#float tensor
c = torch.FloatTensor([[1,2,3], [2,2,1], [4,7,8], [0,0,0]])
#or we can do
#c = torch.tensor([[1,2,3], [2,2,1], [4,7,8], [0,0,0]], dtype=torch.float)

In [9]:
#there are different kinds of tensors,check website for details
#double tensor
d = torch.DoubleTensor([[1,2,3], [2,2,1], [4,7,8], [0,0,0]])
#or we can do
#d = torch.tensor([[1,2,3], [2,2,1], [4,7,8], [0,0,0]], dtype=torch.double)

In [10]:
print(c)
print(c.dtype)

tensor([[1., 2., 3.],
        [2., 2., 1.],
        [4., 7., 8.],
        [0., 0., 0.]])
torch.float32


In [11]:
print(d)
print(d.dtype)
#float64 and double are the same, float32 and float are the same 

tensor([[1., 2., 3.],
        [2., 2., 1.],
        [4., 7., 8.],
        [0., 0., 0.]], dtype=torch.float64)
torch.float64


In [12]:
print(c.mean())

tensor(2.5000)


In [13]:
print(d.mean())

tensor(2.5000, dtype=torch.float64)


In [14]:
#standard deviation
print(c.std())
print(d.std())

tensor(2.6458)
tensor(2.6458, dtype=torch.float64)


## Extremely Important - tensor reshaping/resizing etc.
### we'll need it when implementing our own neural networks
#### the method to reshape a tensor is called view()

In [15]:
#reshape b
#Note: In python, if one of the dimension is -1, it's size can be inferred
#infer means python can find what the other dimension needed to be
print(b.view(-1,1)) 
#b is originally [4,3] or 12*1. As one dim is -1,python infers/recalls as it was 12*1 and reshape it as such
#as view(-1,1) is specified, it will output in a 2D array(one column, one row)

print(b.view(12))
#this line is basically the same thing, just it will reshape it as a 1D, array.
#view(-1,1) is 12*1 and view(12) is just 12

print(b.view(-1,4))
#I'm telling python that i need 4 columns and you can infer -1
#this should output as 3*4; because i already specified the 4, python inferred the 3

print(b.view(3,4))
#same as previous(-1,4), just this time i didn't use the -1 handy trick, i inferred the 3 myself

#Assign to a new shape
b = b.view(1,-1) #we're telling we need 1 row, and infer the columns(12 columns)
print(b) #should output in 1*12
print(b.shape) #shows us that it is 1*12
print('\n')

#create a tensor with 2 channels, 3 rows, 4 columns (channels, rows, columns)
#(channels, rows, columns) is the format for PyTorch framework, other frameworks differ
three_dim = torch.randn(2,3,4) #two channels, 3*4 each
print('\n')
print(three_dim)
print(three_dim.view(2,12)) #reshape three_dim into a 2row-12col tensor, 2*12 tensor
print(three_dim.view(2,-1)) #it's the same, u know,right? :) 

tensor([[1],
        [2],
        [3],
        [2],
        [2],
        [1],
        [4],
        [7],
        [8],
        [0],
        [0],
        [0]])
tensor([1, 2, 3, 2, 2, 1, 4, 7, 8, 0, 0, 0])
tensor([[1, 2, 3, 2],
        [2, 1, 4, 7],
        [8, 0, 0, 0]])
tensor([[1, 2, 3, 2],
        [2, 1, 4, 7],
        [8, 0, 0, 0]])
tensor([[1, 2, 3, 2, 2, 1, 4, 7, 8, 0, 0, 0]])
torch.Size([1, 12])




tensor([[[-0.0080, -0.8702, -0.2734, -0.3860],
         [ 0.7303,  2.8360, -1.1450,  0.0061],
         [ 0.9107, -0.4292,  1.4238,  1.0228]],

        [[ 2.1354, -0.2115, -1.3541, -1.0112],
         [ 0.5735,  1.6221,  0.3752, -0.1869],
         [ 0.4616, -0.5920, -0.2509,  1.3222]]])
tensor([[-0.0080, -0.8702, -0.2734, -0.3860,  0.7303,  2.8360, -1.1450,  0.0061,
          0.9107, -0.4292,  1.4238,  1.0228],
        [ 2.1354, -0.2115, -1.3541, -1.0112,  0.5735,  1.6221,  0.3752, -0.1869,
          0.4616, -0.5920, -0.2509,  1.3222]])
tensor([[-0.0080, -0.8702, -0.2734, -0.3860,  0.7303

In [16]:
#Create a matrix/tensor with random numbers between 0 and 1
r = torch.rand(4,4) #creating 4*4 tensor
print(r)

tensor([[0.3183, 0.6342, 0.9693, 0.5506],
        [0.1913, 0.2485, 0.6919, 0.7016],
        [0.0598, 0.9248, 0.0024, 0.5493],
        [0.1592, 0.6709, 0.6996, 0.7687]])


In [17]:
#create a matrix with random numbers taken from normal distribution with mean 0 and variance 1
r2 = torch.randn(4,4) #n for normal distribution and (4,4) creates 4*4 matrix
print(r2)
print(r2.dtype)

tensor([[ 0.1010,  0.6950,  1.7865, -1.0973],
        [-0.6230,  0.8556, -1.0587, -0.7017],
        [ 0.4545,  1.3734,  0.5592,  0.5140],
        [-0.3436, -0.9523,  1.1542, -0.3308]])
torch.float32


In [18]:
#create an array of 5 random integers from values between 6 and 9 (exclusive of 10)
in_array = torch.randint(6,10,(5,)) #1D and not 5 rows, it is 5 columns and a single row
print(in_array)
print(in_array.dtype)

tensor([7, 9, 6, 9, 8])
torch.int64


In [19]:
#create a 2D array/matrix of size 3*3 from 5 random integers from values between 6 and 9 (exclusive of 10)
in_array2 = torch.randint(6,10,(3,3)) #it is 2D, 3 rows and 3 columns
print(in_array2)
print(in_array2.dtype)

tensor([[9, 7, 8],
        [7, 9, 8],
        [8, 9, 7]])
torch.int64


In [20]:
#get the number of elements in an array
print(torch.numel(in_array))
print(torch.numel(in_array2))

5
9


In [21]:
#construct a 3x3 matrix of zeros and of dtype long
z = torch.zeros(3, 3, dtype=torch.long)
print(z)

#construct a 3x3 matrix of ones
o = torch.ones(3,3)
print(o)
print(o.dtype)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.float32


In [22]:
r2_like = torch.randn_like(r2, dtype=torch.double) 
#randn_like is taking random numbers & exact size of r2 to create a new matrix and the dtype of new matrix is double
#random numbers from normal distribution (n stands for normal distribution, right?)
print(r2_like)

tensor([[-0.4005,  0.4035, -1.7697, -0.6331],
        [-0.3055, -0.2288, -1.5383,  0.8958],
        [ 1.1950, -0.3425,  0.0287,  1.3779],
        [-0.7445,  0.4648, -0.7546, -0.9220]], dtype=torch.float64)


In [23]:
#add two tensors, make sure they are of same size and same datatypes
add_result = torch.add(r, r2)
print(add_result)

tensor([[ 4.1929e-01,  1.3292e+00,  2.7558e+00, -5.4666e-01],
        [-4.3169e-01,  1.1042e+00, -3.6679e-01, -1.1367e-04],
        [ 5.1434e-01,  2.2982e+00,  5.6157e-01,  1.0633e+00],
        [-1.8431e-01, -2.8136e-01,  1.8538e+00,  4.3785e-01]])


In [24]:
#in place addition
r2 = r2.add_(r) #translation: r2 = torch.add(r,r2)
print(r2)

tensor([[ 4.1929e-01,  1.3292e+00,  2.7558e+00, -5.4666e-01],
        [-4.3169e-01,  1.1042e+00, -3.6679e-01, -1.1367e-04],
        [ 5.1434e-01,  2.2982e+00,  5.6157e-01,  1.0633e+00],
        [-1.8431e-01, -2.8136e-01,  1.8538e+00,  4.3785e-01]])


## Matrix slicing - it's important

In [25]:
print(r2[:,1]) 
#in r2, items from all the rows which are also in 1-indexed column(2nd column) are sliced (and showed in 1 row).
#1st col is 0 indexed.

print(r2[:,:2])
# items from all the row which are also in 0th,1th column(exclusive of 2th) are sliced

print(r2[:3,:]) 
#all the columns but only first(0-2) 3 rows, exclusive of 4th row(3-indexed row)

num_ten = r2[2,3] #selecting that number in 2nd row's 3rd column
print(num_ten)

print(num_ten.item()) #extract the number out of the tensor

print(r2[2,:]) #all column items which are in 3rd(2-indexed) row

tensor([ 1.3292,  1.1042,  2.2982, -0.2814])
tensor([[ 0.4193,  1.3292],
        [-0.4317,  1.1042],
        [ 0.5143,  2.2982],
        [-0.1843, -0.2814]])
tensor([[ 4.1929e-01,  1.3292e+00,  2.7558e+00, -5.4666e-01],
        [-4.3169e-01,  1.1042e+00, -3.6679e-01, -1.1367e-04],
        [ 5.1434e-01,  2.2982e+00,  5.6157e-01,  1.0633e+00]])
tensor(1.0633)
1.0632529258728027
tensor([0.5143, 2.2982, 0.5616, 1.0633])
